### ISSUE TITLE
Trigger Deletion

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/rapidpro#4484] opened 2023-04-12 16:16 UTC
### Discussed in https://github.com/nyaruka/rapidpro/discussions/4373

<div type='discussions-op-text'>

<sup>Originally posted by **ericnewcomer** March  1, 2023</sup>
Today users can only archive triggers and can never fully delete them. This seems unnecessarily restrictive and makes it harder for them to keep things tidy in their account.</div>

**Comment by rowanseymour** [comment] 2023-04-13 21:30
Dupe of https://github.com/nyaruka/rapidpro/issues/4481

**Closed by rowanseymour** 2023-04-13 21:30 UTC
